name: CI/CD

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        scala: [3.3.1]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (temurin-${{ matrix.java }})
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Build project
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Run scaladoc
        run: sbt doc

  publish:
    name: Publish Release
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Publish to GitHub Packages
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Publish to GitHub Packages (signed)
        if: startsWith(github.ref, 'refs/tags/v')
        run: sbt publishSigned
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }} 